steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker-compose -f docker-compose.yml build

        docker-compose -f docker-compose.yml push

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy music-exercise-tracking-service \
         --image gcr.io/$PROJECT_ID/$(basename $IMAGE):$COMMIT_SHA \
         --region global \

images:
  - "gcr.io/$PROJECT_ID/music-exercise-tracking-service:$COMMIT_SHA"
