
services:
  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env