
services:
  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
      image: frontend:latest
    ports:
      - "3000:3000"
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      image: backend:latest

    env_file:
      - .env