
services:
  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "3000:3000"
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env